# Usar una imagen base adecuada
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de requirements
COPY requirements.txt requirements-test.txt ./

# Instalar las dependencias
RUN pip install -r requirements.txt -r requirements-test.txt

# Copiar el código fuente
COPY . .

# Comando para ejecutar las pruebas
CMD ["pytest"]
